### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://play-fe.googleapis.com/auth

### ISSUE THREAD

**Issue by allaf2** [marzzzello/playstoreapi#1]
how can i solve this?

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://play-fe.googleapis.com/auth

**Comment by marzzzello** [comment]
Can you include the code so I can reproduce it?

**Comment by marzzzello** [comment]
I am gonna close the issue tracker here on GitHub as this only a mirror of the repo on GitLab. You can open an issue there that includes the code to reproduce the issue.
