### ISSUE TITLE
proto

### ISSUE THREAD

**Issue by 89z** [marzzzello/playstoreapi#2]
where did this file come from:

https://github.com/marzzzello/playstoreapi/blob/master/googleplay.proto

**Comment by marzzzello** [comment]
I used the one from Aurora Store
https://gitlab.com/AuroraOSS/gplayapi/-/blob/master/src/main/proto/GooglePlay.proto

**Comment by marzzzello** [comment]
I am gonna close the issue tracker here on GitHub as this only a mirror of the repo on GitLab. If you have more questions or issuess please use the issue tracker on GitLab.
